### ISSUE TITLE
Icon no longer visible after upgrade

### ISSUE THREAD

**Issue by mischapeters** [janstuemmel/theme-switcher#1]
After the last Firefox upgrade the icon of the extension is no longer visible.
I did remove and reinstall to see if that would fix the problem, but it didn't.
Firefox 117.0.1 (64-bit) on macOS 13.5.2 (22G91)
See screenshots.

<img width="259" alt="Screenshot 2023-09-25 at 09 32 02" src="https://github.com/janstuemmel/theme-switcher/assets/7456624/e5a97807-916b-4c26-8e56-7cc472a4f651">

<img width="191" alt="Screenshot 2023-09-25 at 09 32 10" src="https://github.com/janstuemmel/theme-switcher/assets/7456624/d5d9a433-f09e-4d8b-b4ac-b00656879d56">

**Comment by janstuemmel** [comment]
Must have been happend via a firefox update... I will look into this...

https://www.reddit.com/r/FirefoxCSS/comments/myc578/svg_icon_contextfill_resolves_to_black/

**Comment by janstuemmel** [comment]
Fixed by changing icon
https://github.com/janstuemmel/theme-switcher/commit/389f1317adb818201f777a0236fd0dd4a37b6c33
